// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: api/sec_kill/proto/sec_kill.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecKillV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GoodsNum string `protobuf:"bytes,2,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	Num      int32  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *SecKillV1Request) Reset() {
	*x = SecKillV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV1Request) ProtoMessage() {}

func (x *SecKillV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV1Request.ProtoReflect.Descriptor instead.
func (*SecKillV1Request) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{0}
}

func (x *SecKillV1Request) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SecKillV1Request) GetGoodsNum() string {
	if x != nil {
		return x.GoodsNum
	}
	return ""
}

func (x *SecKillV1Request) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SecKillV1Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *SecKillV1ReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecKillV1Reply) Reset() {
	*x = SecKillV1Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV1Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV1Reply) ProtoMessage() {}

func (x *SecKillV1Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV1Reply.ProtoReflect.Descriptor instead.
func (*SecKillV1Reply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{1}
}

func (x *SecKillV1Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SecKillV1Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SecKillV1Reply) GetData() *SecKillV1ReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SecKillV1ReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
}

func (x *SecKillV1ReplyData) Reset() {
	*x = SecKillV1ReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV1ReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV1ReplyData) ProtoMessage() {}

func (x *SecKillV1ReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV1ReplyData.ProtoReflect.Descriptor instead.
func (*SecKillV1ReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{2}
}

func (x *SecKillV1ReplyData) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type SecKillV2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GoodsNum string `protobuf:"bytes,2,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	Num      int32  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *SecKillV2Request) Reset() {
	*x = SecKillV2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV2Request) ProtoMessage() {}

func (x *SecKillV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV2Request.ProtoReflect.Descriptor instead.
func (*SecKillV2Request) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{3}
}

func (x *SecKillV2Request) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SecKillV2Request) GetGoodsNum() string {
	if x != nil {
		return x.GoodsNum
	}
	return ""
}

func (x *SecKillV2Request) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SecKillV2Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *SecKillV2ReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecKillV2Reply) Reset() {
	*x = SecKillV2Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV2Reply) ProtoMessage() {}

func (x *SecKillV2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV2Reply.ProtoReflect.Descriptor instead.
func (*SecKillV2Reply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{4}
}

func (x *SecKillV2Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SecKillV2Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SecKillV2Reply) GetData() *SecKillV2ReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SecKillV2ReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
}

func (x *SecKillV2ReplyData) Reset() {
	*x = SecKillV2ReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV2ReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV2ReplyData) ProtoMessage() {}

func (x *SecKillV2ReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV2ReplyData.ProtoReflect.Descriptor instead.
func (*SecKillV2ReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{5}
}

func (x *SecKillV2ReplyData) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type SecKillV3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GoodsNum string `protobuf:"bytes,2,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	Num      int32  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *SecKillV3Request) Reset() {
	*x = SecKillV3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV3Request) ProtoMessage() {}

func (x *SecKillV3Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV3Request.ProtoReflect.Descriptor instead.
func (*SecKillV3Request) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{6}
}

func (x *SecKillV3Request) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SecKillV3Request) GetGoodsNum() string {
	if x != nil {
		return x.GoodsNum
	}
	return ""
}

func (x *SecKillV3Request) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SecKillV3Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *SecKillV3ReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SecKillV3Reply) Reset() {
	*x = SecKillV3Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV3Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV3Reply) ProtoMessage() {}

func (x *SecKillV3Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV3Reply.ProtoReflect.Descriptor instead.
func (*SecKillV3Reply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{7}
}

func (x *SecKillV3Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SecKillV3Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SecKillV3Reply) GetData() *SecKillV3ReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SecKillV3ReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecNum string `protobuf:"bytes,1,opt,name=secNum,proto3" json:"secNum,omitempty"`
}

func (x *SecKillV3ReplyData) Reset() {
	*x = SecKillV3ReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecKillV3ReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecKillV3ReplyData) ProtoMessage() {}

func (x *SecKillV3ReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecKillV3ReplyData.ProtoReflect.Descriptor instead.
func (*SecKillV3ReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{8}
}

func (x *SecKillV3ReplyData) GetSecNum() string {
	if x != nil {
		return x.SecNum
	}
	return ""
}

type GetGoodsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetGoodsListRequest) Reset() {
	*x = GetGoodsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsListRequest) ProtoMessage() {}

func (x *GetGoodsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsListRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsListRequest) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{9}
}

func (x *GetGoodsListRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetGoodsListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGoodsListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGoodsListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetGoodsListReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetGoodsListReply) Reset() {
	*x = GetGoodsListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsListReply) ProtoMessage() {}

func (x *GetGoodsListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsListReply.ProtoReflect.Descriptor instead.
func (*GetGoodsListReply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{10}
}

func (x *GetGoodsListReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGoodsListReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGoodsListReply) GetData() *GetGoodsListReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGoodsListReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsList []*GoodInfo `protobuf:"bytes,1,rep,name=goodsList,proto3" json:"goodsList,omitempty"`
}

func (x *GetGoodsListReplyData) Reset() {
	*x = GetGoodsListReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsListReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsListReplyData) ProtoMessage() {}

func (x *GetGoodsListReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsListReplyData.ProtoReflect.Descriptor instead.
func (*GetGoodsListReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{11}
}

func (x *GetGoodsListReplyData) GetGoodsList() []*GoodInfo {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

type GetGoodsInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	GoodsNum string `protobuf:"bytes,2,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
}

func (x *GetGoodsInfoRequest) Reset() {
	*x = GetGoodsInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsInfoRequest) ProtoMessage() {}

func (x *GetGoodsInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGoodsInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{12}
}

func (x *GetGoodsInfoRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetGoodsInfoRequest) GetGoodsNum() string {
	if x != nil {
		return x.GoodsNum
	}
	return ""
}

type GetGoodsInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetGoodsInfoReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetGoodsInfoReply) Reset() {
	*x = GetGoodsInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsInfoReply) ProtoMessage() {}

func (x *GetGoodsInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsInfoReply.ProtoReflect.Descriptor instead.
func (*GetGoodsInfoReply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{13}
}

func (x *GetGoodsInfoReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGoodsInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGoodsInfoReply) GetData() *GetGoodsInfoReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGoodsInfoReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsInfo *GoodInfo `protobuf:"bytes,1,opt,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
}

func (x *GetGoodsInfoReplyData) Reset() {
	*x = GetGoodsInfoReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsInfoReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsInfoReplyData) ProtoMessage() {}

func (x *GetGoodsInfoReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsInfoReplyData.ProtoReflect.Descriptor instead.
func (*GetGoodsInfoReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{14}
}

func (x *GetGoodsInfoReplyData) GetGoodsInfo() *GoodInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

type GoodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsNum  string  `protobuf:"bytes,1,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	GoodsName string  `protobuf:"bytes,2,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	Price     float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	PicUrl    string  `protobuf:"bytes,4,opt,name=picUrl,proto3" json:"picUrl,omitempty"`
	Seller    int64   `protobuf:"varint,5,opt,name=seller,proto3" json:"seller,omitempty"`
}

func (x *GoodInfo) Reset() {
	*x = GoodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInfo) ProtoMessage() {}

func (x *GoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInfo.ProtoReflect.Descriptor instead.
func (*GoodInfo) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{15}
}

func (x *GoodInfo) GetGoodsNum() string {
	if x != nil {
		return x.GoodsNum
	}
	return ""
}

func (x *GoodInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *GoodInfo) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodInfo) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *GoodInfo) GetSeller() int64 {
	if x != nil {
		return x.Seller
	}
	return 0
}

type GetSecKillInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SecNum string `protobuf:"bytes,2,opt,name=secNum,proto3" json:"secNum,omitempty"`
}

func (x *GetSecKillInfoRequest) Reset() {
	*x = GetSecKillInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecKillInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecKillInfoRequest) ProtoMessage() {}

func (x *GetSecKillInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecKillInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSecKillInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{16}
}

func (x *GetSecKillInfoRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetSecKillInfoRequest) GetSecNum() string {
	if x != nil {
		return x.SecNum
	}
	return ""
}

type GetSecKillInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetSecKillInfoReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSecKillInfoReply) Reset() {
	*x = GetSecKillInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecKillInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecKillInfoReply) ProtoMessage() {}

func (x *GetSecKillInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecKillInfoReply.ProtoReflect.Descriptor instead.
func (*GetSecKillInfoReply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{17}
}

func (x *GetSecKillInfoReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSecKillInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSecKillInfoReply) GetData() *GetSecKillInfoReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSecKillInfoReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	OrderNum string `protobuf:"bytes,2,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	SecNum   string `protobuf:"bytes,3,opt,name=secNum,proto3" json:"secNum,omitempty"`
	GoodsNum string `protobuf:"bytes,4,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
}

func (x *GetSecKillInfoReplyData) Reset() {
	*x = GetSecKillInfoReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecKillInfoReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecKillInfoReplyData) ProtoMessage() {}

func (x *GetSecKillInfoReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecKillInfoReplyData.ProtoReflect.Descriptor instead.
func (*GetSecKillInfoReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{18}
}

func (x *GetSecKillInfoReplyData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetSecKillInfoReplyData) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *GetSecKillInfoReplyData) GetSecNum() string {
	if x != nil {
		return x.SecNum
	}
	return ""
}

func (x *GetSecKillInfoReplyData) GetGoodsNum() string {
	if x != nil {
		return x.GoodsNum
	}
	return ""
}

type GetOrderListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetOrderListRequest) Reset() {
	*x = GetOrderListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListRequest) ProtoMessage() {}

func (x *GetOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListRequest.ProtoReflect.Descriptor instead.
func (*GetOrderListRequest) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderListRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetOrderListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetOrderInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OrderNum string `protobuf:"bytes,2,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
}

func (x *GetOrderInfoRequest) Reset() {
	*x = GetOrderInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoRequest) ProtoMessage() {}

func (x *GetOrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{20}
}

func (x *GetOrderInfoRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetOrderInfoRequest) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type GetOrderInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetOrderInfoReplyData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetOrderInfoReply) Reset() {
	*x = GetOrderInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReply) ProtoMessage() {}

func (x *GetOrderInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReply.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{21}
}

func (x *GetOrderInfoReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOrderInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOrderInfoReply) GetData() *GetOrderInfoReplyData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOrderInfoReplyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seller   int64   `protobuf:"varint,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Buyer    int64   `protobuf:"varint,2,opt,name=buyer,proto3" json:"buyer,omitempty"`
	OrderNum string  `protobuf:"bytes,3,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	GoodsNum int64   `protobuf:"varint,4,opt,name=goodsNum,proto3" json:"goodsNum,omitempty"`
	Price    float32 `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Status   int32   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetOrderInfoReplyData) Reset() {
	*x = GetOrderInfoReplyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderInfoReplyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoReplyData) ProtoMessage() {}

func (x *GetOrderInfoReplyData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoReplyData.ProtoReflect.Descriptor instead.
func (*GetOrderInfoReplyData) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{22}
}

func (x *GetOrderInfoReplyData) GetSeller() int64 {
	if x != nil {
		return x.Seller
	}
	return 0
}

func (x *GetOrderInfoReplyData) GetBuyer() int64 {
	if x != nil {
		return x.Buyer
	}
	return 0
}

func (x *GetOrderInfoReplyData) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *GetOrderInfoReplyData) GetGoodsNum() int64 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *GetOrderInfoReplyData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetOrderInfoReplyData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetOrderListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetOrderListReply) Reset() {
	*x = GetOrderListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListReply) ProtoMessage() {}

func (x *GetOrderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sec_kill_proto_sec_kill_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListReply.ProtoReflect.Descriptor instead.
func (*GetOrderListReply) Descriptor() ([]byte, []int) {
	return file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP(), []int{23}
}

func (x *GetOrderListReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetOrderListReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_sec_kill_proto_sec_kill_proto protoreflect.FileDescriptor

var file_api_sec_kill_proto_sec_kill_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x22, 0x58, 0x0a, 0x10, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x77,
	0x0a, 0x0e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x4b, 0x69,
	0x6c, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x58, 0x0a, 0x10, 0x53, 0x65, 0x63,
	0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x77, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x32,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x32, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x12,
	0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x32, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x58,
	0x0a, 0x10, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x77, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x4b,
	0x69, 0x6c, 0x6c, 0x56, 0x33, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63,
	0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x56, 0x33, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2c, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x33, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x4e, 0x75, 0x6d, 0x22,
	0x5b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x7d, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x49, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x7d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x37, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x47, 0x6f,
	0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e,
	0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x63, 0x55, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63,
	0x4b, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x4e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x4e, 0x75, 0x6d, 0x22,
	0x81, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x4b, 0x69,
	0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x45, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x7d, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xab, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75,
	0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x75, 0x79, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x41, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xea, 0x04, 0x0a, 0x07, 0x53, 0x65,
	0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x4f, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x56, 0x31, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f,
	0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56,
	0x31, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x56, 0x32, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x32, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63,
	0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x56, 0x32, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x4b, 0x69,
	0x6c, 0x6c, 0x56, 0x33, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b,
	0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x56, 0x33,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x56, 0x33, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x5e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b,
	0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x63, 0x4b, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x58, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x59, 0x0a, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x41,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x74, 0x73, 0x74,
	0x6f, 0x72, 0x6d, 0x68, 0x75, 0x62, 0x2f, 0x62, 0x69, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x2f,
	0x73, 0x65, 0x63, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x63,
	0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sec_kill_proto_sec_kill_proto_rawDescOnce sync.Once
	file_api_sec_kill_proto_sec_kill_proto_rawDescData = file_api_sec_kill_proto_sec_kill_proto_rawDesc
)

func file_api_sec_kill_proto_sec_kill_proto_rawDescGZIP() []byte {
	file_api_sec_kill_proto_sec_kill_proto_rawDescOnce.Do(func() {
		file_api_sec_kill_proto_sec_kill_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sec_kill_proto_sec_kill_proto_rawDescData)
	})
	return file_api_sec_kill_proto_sec_kill_proto_rawDescData
}

var file_api_sec_kill_proto_sec_kill_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_sec_kill_proto_sec_kill_proto_goTypes = []interface{}{
	(*SecKillV1Request)(nil),        // 0: api.sec_kill.v1.SecKillV1Request
	(*SecKillV1Reply)(nil),          // 1: api.sec_kill.v1.SecKillV1Reply
	(*SecKillV1ReplyData)(nil),      // 2: api.sec_kill.v1.SecKillV1ReplyData
	(*SecKillV2Request)(nil),        // 3: api.sec_kill.v1.SecKillV2Request
	(*SecKillV2Reply)(nil),          // 4: api.sec_kill.v1.SecKillV2Reply
	(*SecKillV2ReplyData)(nil),      // 5: api.sec_kill.v1.SecKillV2ReplyData
	(*SecKillV3Request)(nil),        // 6: api.sec_kill.v1.SecKillV3Request
	(*SecKillV3Reply)(nil),          // 7: api.sec_kill.v1.SecKillV3Reply
	(*SecKillV3ReplyData)(nil),      // 8: api.sec_kill.v1.SecKillV3ReplyData
	(*GetGoodsListRequest)(nil),     // 9: api.sec_kill.v1.GetGoodsListRequest
	(*GetGoodsListReply)(nil),       // 10: api.sec_kill.v1.GetGoodsListReply
	(*GetGoodsListReplyData)(nil),   // 11: api.sec_kill.v1.GetGoodsListReplyData
	(*GetGoodsInfoRequest)(nil),     // 12: api.sec_kill.v1.GetGoodsInfoRequest
	(*GetGoodsInfoReply)(nil),       // 13: api.sec_kill.v1.GetGoodsInfoReply
	(*GetGoodsInfoReplyData)(nil),   // 14: api.sec_kill.v1.GetGoodsInfoReplyData
	(*GoodInfo)(nil),                // 15: api.sec_kill.v1.GoodInfo
	(*GetSecKillInfoRequest)(nil),   // 16: api.sec_kill.v1.GetSecKillInfoRequest
	(*GetSecKillInfoReply)(nil),     // 17: api.sec_kill.v1.GetSecKillInfoReply
	(*GetSecKillInfoReplyData)(nil), // 18: api.sec_kill.v1.GetSecKillInfoReplyData
	(*GetOrderListRequest)(nil),     // 19: api.sec_kill.v1.GetOrderListRequest
	(*GetOrderInfoRequest)(nil),     // 20: api.sec_kill.v1.GetOrderInfoRequest
	(*GetOrderInfoReply)(nil),       // 21: api.sec_kill.v1.GetOrderInfoReply
	(*GetOrderInfoReplyData)(nil),   // 22: api.sec_kill.v1.GetOrderInfoReplyData
	(*GetOrderListReply)(nil),       // 23: api.sec_kill.v1.GetOrderListReply
}
var file_api_sec_kill_proto_sec_kill_proto_depIdxs = []int32{
	2,  // 0: api.sec_kill.v1.SecKillV1Reply.data:type_name -> api.sec_kill.v1.SecKillV1ReplyData
	5,  // 1: api.sec_kill.v1.SecKillV2Reply.data:type_name -> api.sec_kill.v1.SecKillV2ReplyData
	8,  // 2: api.sec_kill.v1.SecKillV3Reply.data:type_name -> api.sec_kill.v1.SecKillV3ReplyData
	11, // 3: api.sec_kill.v1.GetGoodsListReply.data:type_name -> api.sec_kill.v1.GetGoodsListReplyData
	15, // 4: api.sec_kill.v1.GetGoodsListReplyData.goodsList:type_name -> api.sec_kill.v1.GoodInfo
	14, // 5: api.sec_kill.v1.GetGoodsInfoReply.data:type_name -> api.sec_kill.v1.GetGoodsInfoReplyData
	15, // 6: api.sec_kill.v1.GetGoodsInfoReplyData.goodsInfo:type_name -> api.sec_kill.v1.GoodInfo
	18, // 7: api.sec_kill.v1.GetSecKillInfoReply.data:type_name -> api.sec_kill.v1.GetSecKillInfoReplyData
	22, // 8: api.sec_kill.v1.GetOrderInfoReply.data:type_name -> api.sec_kill.v1.GetOrderInfoReplyData
	0,  // 9: api.sec_kill.v1.SecKill.SecKillV1:input_type -> api.sec_kill.v1.SecKillV1Request
	3,  // 10: api.sec_kill.v1.SecKill.SecKillV2:input_type -> api.sec_kill.v1.SecKillV2Request
	6,  // 11: api.sec_kill.v1.SecKill.SecKillV3:input_type -> api.sec_kill.v1.SecKillV3Request
	9,  // 12: api.sec_kill.v1.SecKill.GetGoodsList:input_type -> api.sec_kill.v1.GetGoodsListRequest
	16, // 13: api.sec_kill.v1.SecKill.GetSecKillInfo:input_type -> api.sec_kill.v1.GetSecKillInfoRequest
	19, // 14: api.sec_kill.v1.SecKill.GetOrderList:input_type -> api.sec_kill.v1.GetOrderListRequest
	20, // 15: api.sec_kill.v1.SecKill.GetOrderInfo:input_type -> api.sec_kill.v1.GetOrderInfoRequest
	1,  // 16: api.sec_kill.v1.SecKill.SecKillV1:output_type -> api.sec_kill.v1.SecKillV1Reply
	4,  // 17: api.sec_kill.v1.SecKill.SecKillV2:output_type -> api.sec_kill.v1.SecKillV2Reply
	7,  // 18: api.sec_kill.v1.SecKill.SecKillV3:output_type -> api.sec_kill.v1.SecKillV3Reply
	10, // 19: api.sec_kill.v1.SecKill.GetGoodsList:output_type -> api.sec_kill.v1.GetGoodsListReply
	17, // 20: api.sec_kill.v1.SecKill.GetSecKillInfo:output_type -> api.sec_kill.v1.GetSecKillInfoReply
	23, // 21: api.sec_kill.v1.SecKill.GetOrderList:output_type -> api.sec_kill.v1.GetOrderListReply
	21, // 22: api.sec_kill.v1.SecKill.GetOrderInfo:output_type -> api.sec_kill.v1.GetOrderInfoReply
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_sec_kill_proto_sec_kill_proto_init() }
func file_api_sec_kill_proto_sec_kill_proto_init() {
	if File_api_sec_kill_proto_sec_kill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV1Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV1ReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV2Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV2ReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV3Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecKillV3ReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsListReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsInfoReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecKillInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecKillInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecKillInfoReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderInfoReplyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sec_kill_proto_sec_kill_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sec_kill_proto_sec_kill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sec_kill_proto_sec_kill_proto_goTypes,
		DependencyIndexes: file_api_sec_kill_proto_sec_kill_proto_depIdxs,
		MessageInfos:      file_api_sec_kill_proto_sec_kill_proto_msgTypes,
	}.Build()
	File_api_sec_kill_proto_sec_kill_proto = out.File
	file_api_sec_kill_proto_sec_kill_proto_rawDesc = nil
	file_api_sec_kill_proto_sec_kill_proto_goTypes = nil
	file_api_sec_kill_proto_sec_kill_proto_depIdxs = nil
}
